version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
  dev-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: thispassword
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:


